import React, { FC } from 'react';
import Category from '../../../shared/models/Category';
import Budget from '../../../shared/models/Budget';
import { BudgetModalState } from '../types/BudgetModalState';
import { BudgetModalAction } from '../types/BudgetModalAction';
import { ToastTrigger } from '../../../shared/types';
interface IProps {
    fontFamily?: string;
    modalState: BudgetModalState;
    modalDispatch: React.Dispatch<BudgetModalAction>;
    modalTitle: string;
    modalTitleSecond: string;
    modalDetailTitle: string;
    categories: Category[];
    budgets: Budget[];
    formCategoriesText: string;
    formSubcategoriesText: string;
    formCreateButtonText: string;
    formSaveButtonText: string;
    budgetCardMessage: string;
    editButtonText: string;
    deleteButtonText: string;
    showToast: ToastTrigger;
    confirmDeleteDialogTitle: string;
    confirmDeleteDialogMessage: string;
    confirmDeleteDialogNegativeButtonText: string;
    confirmDeleteDialogPositiveButtonText: string;
}
declare const ModalNewBudget: FC<IProps>;
export default ModalNewBudget;
