export declare const CONSENT_REQUESTED_STATUS = "CONSENT_REQUESTED";
export declare const CONSENT_GRANTED_STATUS = "CONSENT_GRANTED";
export declare const CONSENT_DELETED_STATUS = "CONSENT_DELETED";
export declare const AGGREGATION_STARTED_STATUS = "AGGREGATION_STARTED";
export declare const AGGREGATION_COMPLETED_STATUS = "AGGREGATION_COMPLETED";
export declare const PROCESS_FAILED_STATUS = "PROCESS_FAILED";
