"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PROCESS_FAILED_STATUS = exports.AGGREGATION_COMPLETED_STATUS = exports.AGGREGATION_STARTED_STATUS = exports.CONSENT_DELETED_STATUS = exports.CONSENT_GRANTED_STATUS = exports.CONSENT_REQUESTED_STATUS = void 0;
exports.CONSENT_REQUESTED_STATUS = 'CONSENT_REQUESTED';
exports.CONSENT_GRANTED_STATUS = 'CONSENT_GRANTED';
exports.CONSENT_DELETED_STATUS = 'CONSENT_DELETED';
exports.AGGREGATION_STARTED_STATUS = 'AGGREGATION_STARTED';
exports.AGGREGATION_COMPLETED_STATUS = 'AGGREGATION_COMPLETED';
exports.PROCESS_FAILED_STATUS = 'PROCESS_FAILED';
