import IResponseError from '../../../shared/interfaces/IResponseError';
import { Account, Category } from '../../../shared/models';
import TransactionGroup from '../models/TransactionGroup';
import { ICurrentFilterValues, IFormValues, IFilterFormValues } from '../interfaces';
declare type State = {
    fetchAccountsErrors: IResponseError[];
    fetchCategoriesErrors: IResponseError[];
    fetchTransactionsErrors: IResponseError[];
    formValues: IFormValues;
    filterFormValues: IFilterFormValues;
    currentFilterValues: ICurrentFilterValues;
    isFetchingAccounts: boolean;
    isFetchingCategories: boolean;
    isFetchingTransactions: boolean;
    isModalOpen: boolean;
    isFilterModalOpen: boolean;
    accountsData: Account[];
    categoriesData: Category[];
    transactionsData: TransactionGroup[];
};
export type { State };
