import { ListState } from './types/ListState';
export declare const PREFIX_CLASS: string;
export declare const INITIAL_VALUES: {
    id: string;
    userId: string;
    financialEntityId: string;
    nature: string;
    name: string;
    number: string;
    balance: string;
    balanceType: string;
    chargeable: boolean;
};
export declare const LIST_INITIAL_STATE: ListState;
export declare const DEFAULT_MAIN_PROPS: {
    accountsData: never[];
    financialEntitiesData: never[];
    title: null;
    titleShow: boolean;
    newAccountDisabled: boolean;
    editAccountDisabled: boolean;
    deleteAccountDisabled: boolean;
    newAccountSubmitButton: null;
    deleteAccountButton: null;
    editAccountSubmitButton: null;
    newAccountModalTitle: null;
    editAccountModalTitle: null;
    debitAndCashSectionTitle: null;
    debitAndCashSectionOrder: number;
    debitAndCashSectionShow: boolean;
    creditCardAndDebtSectionTitle: null;
    creditCardAndDebtSectionOrder: number;
    creditCardAndDebtSectionShow: boolean;
    shortTermBalanceSectionTitle: null;
    shortTermBalanceSectionOrder: number;
    shortTermBalanceSectionShow: boolean;
    investmentsSectionTitle: null;
    investmentsSectionOrder: number;
    investmentsSectionShow: boolean;
    creditsSectionTitle: null;
    creditsSectionOrder: number;
    creditsSectionShow: boolean;
    longTermBalanceSectionTitle: null;
    longTermBalanceSectionOrder: number;
    longTermBalanceSectionShow: boolean;
    totalSectionTitle: null;
    totalSectionOrder: number;
    totalSectionShow: boolean;
};
