import IResume from '../../../shared/interfaces/insights/IResume';
import ICategory from '../../../shared/interfaces/ICategory';
import ISharedProperties from '../../../shared/interfaces/IProperties';
import ICommonProps from '../../../shared/interfaces/ICommonProps';
export interface ISummaryProps extends ISharedProperties, ICommonProps {
    analysisExpensesTableAverageTitle: string | null;
    analysisExpensesTableDescrTitle: string | null;
    analysisExpensesTableNumTranTitle: string | null;
    analysisExpensesTableSubTitle: string | null;
    analysisExpensesTableTitle: string | null;
    analysisExpensesTableTotalTitle: string | null;
    analysisIncomesTableAmountTitle: string | null;
    analysisIncomesTableCategoryTitle: string | null;
    analysisIncomesTableConceptTitle: string | null;
    analysisIncomesTableDateTitle: string | null;
    analysisIncomesTableSubTitle: string | null;
    analysisIncomesTableTitle: string | null;
    cardBalanceChartTitle: string | null;
    cardBalanceExpenseTitle: string | null;
    cardBalanceIncomeTitle: string | null;
    cardBalanceTitle: string | null;
    cardExpensesBarChartTitle: string | null;
    cardExpensesCatTableTitle: string | null;
    cardExpensesDonChartTitle: string;
    cardExpensesSubcatTableTitle: string | null;
    cardExpensesTotalTitle: string | null;
    cardIncomesBarChartTitle: string | null;
    cardIncomesCatTableTitle: string | null;
    cardIncomesDonChartTitle: string;
    cardIncomesSubcatTableTitle: string | null;
    cardIncomesTotalTitle: string | null;
    categoryExpensesTableAmountTitle: string | null;
    categoryExpensesTableConceptTitle: string | null;
    categoryExpensesTableDetailTitle: string | null;
    categoryExpensesTablePercentTitle: string | null;
    categoryIncomesTableAmountTitle: string | null;
    categoryIncomesTableConceptTitle: string | null;
    categoryIncomesTableDetailTitle: string | null;
    categoryIncomesTablePercentTitle: string | null;
    expensesBarChartColor: string;
    expensesBarChartSelectedColor: string;
    iconExpensesAnalysisTooltip: string | null;
    iconExpensesTransactionTooltip: string | null;
    iconIncomesAnalysisTooltip: string | null;
    iconIncomesTransactionTooltip: string | null;
    incomesBarChartColor: string;
    incomesBarChartSelectedColor: string;
    subcategoryExpensesTableAmountTitle: string | null;
    subcategoryExpensesTableConceptTitle: string | null;
    subcategoryExpensesTableTransactionsTitle: string | null;
    subcategoryExpensesTablePercentTitle: string | null;
    subcategoryIncomesTableAmountTitle: string | null;
    subcategoryIncomesTableConceptTitle: string | null;
    subcategoryIncomesTableTransactionsTitle: string | null;
    subcategoryIncomesTablePercentTitle: string | null;
    summaryTitle: string | null;
    tabBalanceTitle: string | null;
    tabExpensesTitle: string | null;
    tabIncomesTitle: string | null;
    summaryData: IResume | string;
    categoriesData: ICategory[] | string;
    isEmpty: boolean;
    emptyViewTitle: string | null;
    emptyViewDescription: string | null;
    emptyViewActionText: string | null;
}
