import IFilterOptions from '../interfaces/IFilterOptions';
export default class FilterOptions implements IFilterOptions {
    private _minAmount?;
    private _maxAmount?;
    private _categoryId?;
    private _subcategoryId?;
    private _withCharges?;
    private _withDebits?;
    private _accountId?;
    private _dateFrom?;
    private _dateTo?;
    constructor(initValue?: IFilterOptions);
    get minAmount(): string | undefined;
    set minAmount(value: string | undefined);
    get maxAmount(): string | undefined;
    set maxAmount(value: string | undefined);
    get categoryId(): string | undefined;
    set categoryId(value: string | undefined);
    get subcategoryId(): string | undefined;
    set subcategoryId(value: string | undefined);
    get withCharges(): string | undefined;
    set withCharges(value: string | undefined);
    get withDebits(): string | undefined;
    set withDebits(value: string | undefined);
    get accountId(): string | undefined;
    set accountId(value: string | undefined);
    get dateFrom(): string | undefined;
    set dateFrom(value: string | undefined);
    get dateTo(): string | undefined;
    set dateTo(value: string | undefined);
    toObject(): IFilterOptions;
}
